routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    return redirect()->to('/films');
});

// RESTful Api for Film

Route::post('api/film/store','FilmController@apiStore');
Route::get('api/film/{slug}','FilmController@apiShow');
Route::get('api/film','FilmController@getFilms');
Route::patch('api/update/{slug}','FilmController@apiUpdate');
Route::delete('api/film/{slug}','FilmController@apiDelete');




Auth::routes(['verify' => true]);

Route::get('/home',  function () {
    return redirect()->to('/films');
});


Route::get('films','FilmController@index');

Route::resource('/film','FilmController')->except([
     'update', 'index','destroy'
]);
Route::post('comment/{id}','CommentController@store');

app/Film.php
<?php

namespace App;

use App\Helpers\CountriesHelper;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Collection;

class Film extends Model
{
    use SoftDeletes;
    protected $fillable=['name','description','release_date','ticket_price','rating','photo','slug','country','genres'];
    protected $with=['comments','user'];
    protected $perPage = 1;

    public function comments()
    {
        return $this->hasMany('App\Comment');
    }
    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function getGenresAttribute($value){
        $genres=explode(',',$value);
        return implode(',',Genre::whereIn('id',$genres)->pluck('name')->toArray());
    }
    public function getCountryAttribute($value){
        foreach (CountriesHelper::getCountrylist() as $index=>$country){
            if($index==$value)
                return $country['name'];
        }
    }

    protected $dates = ['deleted_at'];
}

app/Http/Controllers/FilmController.php
<?php

namespace App\Http\Controllers;

use App\Film;
use App\Genre;
use App\Helpers\CountriesHelper;
use App\Http\Requests\AddFilmRequest;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class FilmController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('film.index');
    }
    public function getFilms(){
        return Film::paginate();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if(Auth::check()){
            $genres=Genre::all();
            $countries=CountriesHelper::getCountrylist();
            return view('film.create')
                ->withGenres($genres)
                ->withCountries($countries);
        }
        return redirect()->to('/login');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function apistore(AddFilmRequest $request)
    {
        if(Auth::check()){
            $photo=$request->file('photo');
            $directory='/images/';
            $name=str_slug($request->name.'-'.$request->country).'.'.$photo->clientExtension();
            $photo->move(public_path($directory),$name);
            $photo=$directory.$name;

            $user=Auth::user();
            $user->films()->create([
                'name'=>$request->name,
                'description'=>$request->description,
                'rating'=>$request->rating,
                'ticket_price'=>$request->ticket_price,
                'country'=>$request->country,
                'genres'=>$request->genres,
                'release_date'=>$request->release_date,
                'slug'=>str_slug($request->name.'-'.$request->country),
                'photo'=>$photo,
            ]);
            return response()->json(['sucess'=>'true'],200);
        }

        return response()->json(['sucess'=>'false'],500);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($slug)
    {
        return view('film.show')->withSlug($slug);
    }
    public function apiShow($slug){
        $film=Film::where('slug',$slug)->first();
        if($film==null)
            return response(['success'=>'false'],404);
        return $film;
    }
    public function apiUpdate($slug,AddFilmRequest $request){
        if(Auth::check()){
            $user=Auth::user();
            $user->films()->where('slug',$slug)->first()->update($request->all());
            return response()->json(['success'=>'true'],202);
        }
        return response()->json(['success'=>'false'],401);
    }

    public function apiDelete($slug)
    {
        if(Auth::check()){
            $film=Film::where('slug',$slug)->first();
            $user=Auth::user();
            if($film==null)
                return response(['success'=>'false'],404);
            if($film->user_id==$user->id){
                $film->comments()->delete();
                $film->delete();
                return response()->json(['success'=>'true'],202);
            }
        }
        return response()->json(['success'=>'false'],401);
    }

}

resources/views/film/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <add-film inline-template>
                <div class="col-md-8">
                    <div class="card">
                        <div class="card-header">{{ __('Add Film') }}</div>

                        <div class="card-body">
                            <form method="POST" action="{{ route('film.store') }}" enctype="multipart/form-data">


                                <div class="form-group row">
                                    <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Film Name') }}</label>

                                    <div class="col-md-6">
                                        <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" v-model="name">


                                            <span v-if="errors.name!==undefined" class="text-danger">
                                                <strong>@{{ errors.name[0] }}</strong>
                                            </span>
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label for="description" class="col-md-4 col-form-label text-md-right">{{ __('Film Description') }}</label>

                                    <div class="col-md-6">
                                        <textarea id="description" rows='10' type="text" class="form-control{{ $errors->has('description') ? ' is-invalid' : '' }}" name="description" required v-model="description">{{ old('description') }}</textarea>

                                        <span v-if="errors.description!==undefined" class="text-danger">
                                                <strong>@{{ errors.description[0] }}</strong>
                                            </span>
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label for="release_date" class="col-md-4 col-form-label text-md-right">{{ __('Release Date') }}</label>

                                    <div class="col-md-6">
                                        <input id="release_date" type="date" class="form-control{{ $errors->has('release_date') ? ' is-invalid' : '' }}" name="release_date" value="{{ old('release_date') }}" required v-model="release_date">

                                        <span v-if="errors.release_date!==undefined" class="text-danger">
                                                <strong>@{{ errors.release_date[0] }}</strong>
                                            </span>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label for="rating" class="col-md-4 col-form-label text-md-right">{{ __('Rating') }}</label>

                                    <div class="col-md-6">
                                        <input id="rating" type="text" class="form-control{{ $errors->has('rating') ? ' is-invalid' : '' }}" name="rating" value="{{ old('rating') }}" v-model="rating" required>

                                        <span v-if="errors.rating!==undefined" class="text-danger">
                                                <strong>@{{ errors.rating[0] }}</strong>
                                            </span>
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label for="ticket_price" class="col-md-4 col-form-label text-md-right">{{ __('Ticket Price') }}</label>

                                    <div class="col-md-6">
                                        <input id="ticket_price" type="text" class="form-control{{ $errors->has('ticket_price') ? ' is-invalid' : '' }}" name="ticket_price" v-model="ticket_price" value="{{ old('ticket_price') }}" required>

                                        <span v-if="errors.ticket_price!==undefined" class="text-danger">
                                                <strong>@{{ errors.ticket_price[0] }}</strong>
                                            </span>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label for="country" class="col-md-4 col-form-label text-md-right">{{ __('Country') }}</label>

                                    <div class="col-md-6">
                                        <select name="country" class="form-control" v-model="country">
                                            @foreach($countries as $index => $country)
                                                <option value="{{$index}}" @if($index==old('country')) selected @endif>{{$country['name']}}</option>
                                            @endforeach
                                        </select>

                                        <span v-if="errors.country!==undefined" class="text-danger">
                                                <strong>@{{ errors.country[0] }}</strong>
                                            </span>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label for="genres" class="col-md-4 col-form-label text-md-right">{{ __('Genres') }}</label>
                                    <div class="col-md-6">
                                        @foreach($genres as $genre)
                                            <div class="form-check">
                                                <input class="form-check-input" name='genres[]' type="checkbox" value="{{$genre->id}}" v-model="genres" >
                                                <label class="form-check-label" >
                                                    {{$genre->name}}
                                                </label>
                                            </div>
                                        @endforeach
                                            <span v-if="errors.genres!==undefined" class="text-danger">
                                                <strong>@{{ errors.genres[0] }}</strong>
                                            </span>
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label for="photo" class="col-md-4 col-form-label text-md-right">{{ __('Photo') }}</label>

                                    <div class="col-md-6">
                                        <input id="photo" type="file" accept="image/*" class="form-control-file{{ $errors->has('photo') ? ' is-invalid' : '' }}" name="photo" value="{{ old('photo') }}" @change="setPhoto" required>

                                        <span v-if="errors.photo!==undefined" class="text-danger">
                                                <strong>@{{ errors.photo[0] }}</strong>
                                            </span>
                                    </div>
                                </div>
                                <div class="form-group row mb-0">
                                    <div class="col-md-6 offset-md-4">
                                        <button type="submit" class="btn btn-primary" @click.prevent="submit">
                                            {{ __('Add') }}
                                        </button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </add-film>
        </div>
    </div>
@endsection

resources/views/film/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <add-film inline-template>
                <div class="col-md-8">
                    <div class="card">
                        <div class="card-header">{{ __('Add Film') }}</div>

                        <div class="card-body">
                            <form method="POST" action="{{ route('film.store') }}" enctype="multipart/form-data">


                                <div class="form-group row">
                                    <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Film Name') }}</label>

                                    <div class="col-md-6">
                                        <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" v-model="name">


                                            <span v-if="errors.name!==undefined" class="text-danger">
                                                <strong>@{{ errors.name[0] }}</strong>
                                            </span>
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label for="description" class="col-md-4 col-form-label text-md-right">{{ __('Film Description') }}</label>

                                    <div class="col-md-6">
                                        <textarea id="description" rows='10' type="text" class="form-control{{ $errors->has('description') ? ' is-invalid' : '' }}" name="description" required v-model="description">{{ old('description') }}</textarea>

                                        <span v-if="errors.description!==undefined" class="text-danger">
                                                <strong>@{{ errors.description[0] }}</strong>
                                            </span>
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label for="release_date" class="col-md-4 col-form-label text-md-right">{{ __('Release Date') }}</label>

                                    <div class="col-md-6">
                                        <input id="release_date" type="date" class="form-control{{ $errors->has('release_date') ? ' is-invalid' : '' }}" name="release_date" value="{{ old('release_date') }}" required v-model="release_date">

                                        <span v-if="errors.release_date!==undefined" class="text-danger">
                                                <strong>@{{ errors.release_date[0] }}</strong>
                                            </span>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label for="rating" class="col-md-4 col-form-label text-md-right">{{ __('Rating') }}</label>

                                    <div class="col-md-6">
                                        <input id="rating" type="text" class="form-control{{ $errors->has('rating') ? ' is-invalid' : '' }}" name="rating" value="{{ old('rating') }}" v-model="rating" required>

                                        <span v-if="errors.rating!==undefined" class="text-danger">
                                                <strong>@{{ errors.rating[0] }}</strong>
                                            </span>
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label for="ticket_price" class="col-md-4 col-form-label text-md-right">{{ __('Ticket Price') }}</label>

                                    <div class="col-md-6">
                                        <input id="ticket_price" type="text" class="form-control{{ $errors->has('ticket_price') ? ' is-invalid' : '' }}" name="ticket_price" v-model="ticket_price" value="{{ old('ticket_price') }}" required>

                                        <span v-if="errors.ticket_price!==undefined" class="text-danger">
                                                <strong>@{{ errors.ticket_price[0] }}</strong>
                                            </span>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label for="country" class="col-md-4 col-form-label text-md-right">{{ __('Country') }}</label>

                                    <div class="col-md-6">
                                        <select name="country" class="form-control" v-model="country">
                                            @foreach($countries as $index => $country)
                                                <option value="{{$index}}" @if($index==old('country')) selected @endif>{{$country['name']}}</option>
                                            @endforeach
                                        </select>

                                        <span v-if="errors.country!==undefined" class="text-danger">
                                                <strong>@{{ errors.country[0] }}</strong>
                                            </span>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label for="genres" class="col-md-4 col-form-label text-md-right">{{ __('Genres') }}</label>
                                    <div class="col-md-6">
                                        @foreach($genres as $genre)
                                            <div class="form-check">
                                                <input class="form-check-input" name='genres[]' type="checkbox" value="{{$genre->id}}" v-model="genres" >
                                                <label class="form-check-label" >
                                                    {{$genre->name}}
                                                </label>
                                            </div>
                                        @endforeach
                                            <span v-if="errors.genres!==undefined" class="text-danger">
                                                <strong>@{{ errors.genres[0] }}</strong>
                                            </span>
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label for="photo" class="col-md-4 col-form-label text-md-right">{{ __('Photo') }}</label>

                                    <div class="col-md-6">
                                        <input id="photo" type="file" accept="image/*" class="form-control-file{{ $errors->has('photo') ? ' is-invalid' : '' }}" name="photo" value="{{ old('photo') }}" @change="setPhoto" required>

                                        <span v-if="errors.photo!==undefined" class="text-danger">
                                                <strong>@{{ errors.photo[0] }}</strong>
                                            </span>
                                    </div>
                                </div>
                                <div class="form-group row mb-0">
                                    <div class="col-md-6 offset-md-4">
                                        <button type="submit" class="btn btn-primary" @click.prevent="submit">
                                            {{ __('Add') }}
                                        </button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </add-film>
        </div>
    </div>
@endsection

resources/views/film/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-10">
                   <films inline-template>
                       <div>
                           <div class="card"  v-for="film in filmsData.data">
                               <img class="card-img-top d-block mx-auto" style="max-width: 400px" :src="film.photo" >
                               <div class="card-body">
                                   <h5 class="card-title">@{{ film.name }}</h5>
                                   <p class="card-text">@{{ film.description }}</p>
                               </div>
                               <ul class="list-group list-group-flush">
                                   <li class="list-group-item">{{__('Released Date:')}} @{{ film.release_date }}</li>
                                   <li class="list-group-item">{{__('Rating: ')}} @{{ film.rating }} <i class="far fa-star"></i></li>
                                   <li class="list-group-item">{{__('Comments: ')}} @{{ film.comments.length }} </li>
                               </ul>
                               <div class="card-body">
                                   <a :href="'{{URL::to('/film')}}/'+film.slug" class="card-link">See Details</a>
                               </div>
                           </div>
                           <br>
                           <div class="text-center">
                              {{__('Total Films: ')}} @{{ filmsData.total }}
                           </div>
                           <nav aria-label="Page navigation example">
                               <ul class="pagination justify-content-center">
                                   <li class="page-item" v-if="filmsData.prev_page_url">
                                       <a class="page-link" @click.prevent="prevPage">Prev</a>
                                   </li>
                                   <li class="page-item disabled" v-else >
                                       <a class="page-link" href="#">Prev</a>
                                   </li>
                                   <li class="page-item disabled"><a class="page-link" href="#">@{{ filmsData.current_page }}</a></li>
                                   <li class="page-item" v-if="filmsData.next_page_url">
                                       <a class="page-link" @click.prevent="nextPage">Next</a>
                                   </li>
                                   <li class="page-item disabled" v-else >
                                       <a class="page-link" href="#">Next</a>
                                   </li>
                               </ul>
                           </nav>
                       </div>
                   </films>

            </div>
        </div>
    </div>
@endsection

resources/views/film/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-10">
              <show-film :slug="{{json_encode($slug)}}" @auth :user="{{ json_encode(Auth::user()) }}"@else :user='-1' @endauth inline-template>
                  <div class="card mb-3 ">
                      <img class="card-img-top d-block mx-auto" style="max-width: 600px" :src="film.photo" >
                      <div class="text-right mr-2">
                          <button class="btn btn-danger" v-if="user.id!==undefined && user.id==film.user.id" @click="deleteFilm">Delete</button>
                      </div>
                      <div class="card-body ">
                          <h5 class="card-title">@{{film.name}}</h5>
                          <p class="card-text">@{{film.description}}</p>
                          <p class="card-text"><small class="text-muted">{{__('Released: ')}} @{{film.release_date}}</small></p>
                          <ul class="list-group list-group-flush">
                              <li class="list-group-item">{{__('Rating: ')}}@{{film.rating}} <i class="far fa-star"></i></li>
                              <li class="list-group-item">{{__('Ticket Price: ')}} @{{film.ticket_price}}</li>
                              <li class="list-group-item">{{__('Country: ')}} @{{film.country}}</li>
                              <li class="list-group-item">{{__('Genres: ')}}

                                      @{{ film.genres }}




                              </li>
                          </ul>
                          <p class="card-text mt-2"><small class="text-muted">{{__('Added By: ')}} @{{film.user.name}}</small> </p>
                      </div>
                      <comments :comments="film.comments"   :film="film.id" inline-template>
                          <div class="card-body">
                              <div class="d-flex mb-2"  style="background: #fafafa" v-for="comment in comments">
                                  <div class="m-3">
                                      <img src="http://www.gravatar.com/avatar/67e75efcdd743a5fa9b8bb12e0a94152.jpg?s=80&d=mm&r=g" alt="" class="d-block mx-auto mb-2 rounded-circle">
                                      @{{comment.user.name}}
                                  </div>
                                  <div class="ml-2 mt-4">
                                      <h5 >@{{comment.name}}</h5>
                                      <p>@{{comment.comment}}</p>
                                  </div>
                              </div>
                              <hr>
                              @auth
                                  <div class="row">
                                      <div class="col-sm-10">
                                          <input type="name" placeholder="Name" class="form-control mb-2" v-model="name" required >
                                          <strong class="text-danger" v-if="errors.name!==undefined">@{{ errors.name[0] }}</strong>
                                          <textarea name="" id="" rows="5" placeholder="Write your comment" class="form-control" v-model="comment">{{__('Write a Comment')}}</textarea>
                                          <strong class="text-danger" v-if="errors.comment!==undefined">@{{ errors.comment[0] }}</strong>
                                      </div>
                                      <div class="col-sm-2">
                                          <button class="btn btn-success" @click="submitComment">
                                              Comment
                                          </button>
                                      </div>
                                  </div>
                              @else
                                  <div class="d-block mb-2 mx-auto"  style="background: #fafafa">
                                      <h4>{{__('Please ')}} <a href="/login" class="">{{__('Login')}}</a> {{(' to Write a comment')}}</h4>
                                  </div>
                              @endauth
                          </div>
                      </comments>
                  </div>
              </show-film>
            </div>
        </div>
    </div>
@endsection